unit definitions;

{$mode ObjFPC}{$H+}

interface

uses
  Classes, SysUtils;




type


 elem_stream_type = record
    strm_typ   : byte;
    elem_typ   : byte;
    sdes        : string;
    ldes        : string;
  end;



const
  TS_TYPE_UNO = $0000;
  TS_TYPE_RSV = $0002;
  TS_TYPE_USR = $00C0;
  TS_TYPE_VID = $00C2;
  TS_TYPE_AUD = $00C3;
  TS_TYPE_ECM = $00C4;

  //Each elementary stream in a transport stream is identified by an 8-bit elementary stream type assignment.
  //Use array index to get its type
  STREAM_TYPE_TABLE : array of elem_stream_type = (
  (strm_typ:$00; elem_typ:TS_TYPE_RSV; sdes:'Reserved'; ldes:'ITU-T|ISO/IEC Reserved'),
  (strm_typ:$01; elem_typ:TS_TYPE_VID; sdes:'MPEG-1 Video'; ldes:'ISO/IEC 11172-2 (MPEG-1 video)'),
  (strm_typ:$02; elem_typ:TS_TYPE_VID; sdes:'MPEG-2 Video'; ldes:'ITU-T Rec. H.262 and ISO/IEC 13818-2 (MPEG-2 higher rate interlaced video)'),
  (strm_typ:$03; elem_typ:TS_TYPE_AUD; sdes:'MPEG-1 Audio'; ldes:'ISO/IEC 11172-3 (MPEG-1 audio)'),
  (strm_typ:$04; elem_typ:TS_TYPE_AUD; sdes:'MPEG-2 Audio'; ldes:'ISO/IEC 13818-3 (MPEG-2 halved sample rate audio)'),
  (strm_typ:$05; elem_typ:TS_TYPE_USR; sdes:'Private'; ldes:'ITU-T Rec. H.222 and ISO/IEC 13818-1 (MPEG-2 tabled data)'),
  (strm_typ:$06; elem_typ:TS_TYPE_AUD; sdes:'AC3|TT|LPCM'; ldes:'ITU-T Rec. H.222 and ISO/IEC 13818-1 (MPEG-2 packetized data) '+
                                                                'privately defined (i.e., DVB subtitles/VBI and AC-3)'),
  (strm_typ:$07; elem_typ:TS_TYPE_USR; sdes:'MHEG'; ldes:'ISO/IEC 13522 (MHEG)'),
  (strm_typ:$08; elem_typ:TS_TYPE_USR; sdes:'DSM-CC'; ldes:'ITU-T Rec. H.222 and ISO/IEC 13818-1 DSM CC'),
  (strm_typ:$09; elem_typ:TS_TYPE_USR; sdes:'H.222.1'; ldes:'ITU-T Rec. H.222 and ISO/IEC 13818-1/11172-1 auxiliary data'),
  (strm_typ:$0A; elem_typ:TS_TYPE_USR; sdes:'13818-6 type A'; ldes:'ISO/IEC 13818-6 DSM CC multiprotocol encapsulation '),
  (strm_typ:$0B; elem_typ:TS_TYPE_USR; sdes:'13818-6 type B'; ldes:'ISO/IEC 13818-6 DSM CC U-N messages'),
  (strm_typ:$0C; elem_typ:TS_TYPE_USR; sdes:'13818-6 type C'; ldes:'ISO/IEC 13818-6 DSM CC stream descriptors'),
  (strm_typ:$0D; elem_typ:TS_TYPE_USR; sdes:'13818-6 type D'; ldes:'SO/IEC 13818-6 DSM CC tabled data '),
  (strm_typ:$0E; elem_typ:TS_TYPE_USR; sdes:'Auxiliary'; ldes:'ISO/IEC 13818-1 auxiliary data'),
  (strm_typ:$0F; elem_typ:TS_TYPE_AUD; sdes:'AAC ADTS'; ldes:'ISO/IEC 13818-7 ADTS AAC (MPEG-2 lower bit-rate audio)'),
  (strm_typ:$10; elem_typ:TS_TYPE_VID; sdes:'MPEG-4'; ldes:'ISO/IEC 14496-2 (MPEG-4 H.263 based video)'),
  (strm_typ:$11; elem_typ:TS_TYPE_AUD; sdes:'AAC LATM'; ldes:'ISO/IEC 14496-3 (MPEG-4 LOAS multi-format framed audio)'),
  (strm_typ:$12; elem_typ:TS_TYPE_AUD; sdes:'MPEG-4'; ldes:'ISO/IEC 14496-1 (MPEG-4 FlexMux)'),
  (strm_typ:$13; elem_typ:TS_TYPE_AUD; sdes:'MPEG-4'; ldes:'ISO/IEC 14496-1 (MPEG-4 FlexMux)'),
  (strm_typ:$14; elem_typ:TS_TYPE_USR; sdes:'MPEG-2'; ldes:'ISO/IEC 13818-6 DSM CC synchronized download protocol '),
  (strm_typ:$15; elem_typ:TS_TYPE_USR; sdes:'MPEG-2'; ldes:'Metadata carried in PES packets'),
  (strm_typ:$16; elem_typ:TS_TYPE_USR; sdes:'MPEG-2'; ldes:'Metadata carried in metadata_sections'),
  (strm_typ:$17; elem_typ:TS_TYPE_USR; sdes:'MPEG-2'; ldes:'ISO/IEC 13818-6 DSM CC Data Carousel metadata'),
  (strm_typ:$18; elem_typ:TS_TYPE_USR; sdes:'MPEG-2'; ldes:'ISO/IEC 13818-6 DSM CC Object Carousel metadata'),
  (strm_typ:$19; elem_typ:TS_TYPE_USR; sdes:'MPEG-2'; ldes:'ISO/IEC 13818-6 Synchronized Download Protocol metadata'),
  (strm_typ:$1A; elem_typ:TS_TYPE_USR; sdes:'IPMP'; ldes:'ISO/IEC 13818-11 IPMP)'),
  (strm_typ:$1B; elem_typ:TS_TYPE_VID; sdes:'H.264'; ldes:'ITU-T Rec. H.264 and ISO/IEC 14496-10 (lower bit-rate video)'),
  (strm_typ:$1C; elem_typ:TS_TYPE_AUD; sdes:'MPEG-4'; ldes:'ISO/IEC 14496-3 (MPEG-4 raw audio)'),
  (strm_typ:$1D; elem_typ:TS_TYPE_USR; sdes:'MPEG-4'; ldes:'ISO/IEC 14496-17 (MPEG-4 text)'),
  (strm_typ:$1E; elem_typ:TS_TYPE_VID; sdes:'MPEG-4'; ldes:'ISO/IEC 23002-3 (MPEG-4 auxiliary video)'),
  (strm_typ:$1F; elem_typ:TS_TYPE_RSV; sdes:'SVC'; ldes:'ISO/IEC 14496-10 SVC (MPEG-4 AVC sub-bitstream)'),
  (strm_typ:$20; elem_typ:TS_TYPE_VID; sdes:'MVC'; ldes:'ISO/IEC 14496-10 MVC (MPEG-4 AVC sub-bitstream)'),
  (strm_typ:$21; elem_typ:TS_TYPE_VID; sdes:'JPEG'; ldes:'ITU-T Rec. T.800 and ISO/IEC 15444 (JPEG 2000 video)'),
  (strm_typ:$22; elem_typ:TS_TYPE_RSV; sdes:'Reserved'; ldes:'ITU-T|ISO/IEC Reserved)'),
  (strm_typ:$23; elem_typ:TS_TYPE_RSV; sdes:'Reserved'; ldes:'ITU-T|ISO/IEC Reserved)'),
  (strm_typ:$24; elem_typ:TS_TYPE_VID; sdes:'H.265'; ldes:'ITU-T Rec. H.265 and ISO/IEC 23008-2 (Ultra HD video)'),
  (strm_typ:$25; elem_typ:TS_TYPE_RSV; sdes:'Reserved'; ldes:'ITU-T|ISO/IEC Reserved)'),
  (strm_typ:$26; elem_typ:TS_TYPE_RSV; sdes:'Reserved'; ldes:'ITU-T|ISO/IEC Reserved)'),
  (strm_typ:$27; elem_typ:TS_TYPE_RSV; sdes:'Reserved'; ldes:'ITU-T|ISO/IEC Reserved)'),
  (strm_typ:$28; elem_typ:TS_TYPE_RSV; sdes:'Reserved'; ldes:'ITU-T|ISO/IEC Reserved)'),
  (strm_typ:$29; elem_typ:TS_TYPE_RSV; sdes:'Reserved'; ldes:'ITU-T|ISO/IEC Reserved)'),
  (strm_typ:$2A; elem_typ:TS_TYPE_RSV; sdes:'Reserved'; ldes:'ITU-T|ISO/IEC Reserved)'),
  (strm_typ:$2B; elem_typ:TS_TYPE_RSV; sdes:'Reserved'; ldes:'ITU-T|ISO/IEC Reserved)'),
  (strm_typ:$2C; elem_typ:TS_TYPE_RSV; sdes:'Reserved'; ldes:'ITU-T|ISO/IEC Reserved)'),
  (strm_typ:$2D; elem_typ:TS_TYPE_RSV; sdes:'Reserved'; ldes:'ITU-T|ISO/IEC Reserved)'),
  (strm_typ:$2E; elem_typ:TS_TYPE_RSV; sdes:'Reserved'; ldes:'ITU-T|ISO/IEC Reserved)'),
  (strm_typ:$2F; elem_typ:TS_TYPE_RSV; sdes:'Reserved'; ldes:'ITU-T|ISO/IEC Reserved)'),
  (strm_typ:$30; elem_typ:TS_TYPE_RSV; sdes:'Reserved'; ldes:'ITU-T|ISO/IEC Reserved)'),
  (strm_typ:$31; elem_typ:TS_TYPE_RSV; sdes:'Reserved'; ldes:'ITU-T|ISO/IEC Reserved)'),
  (strm_typ:$32; elem_typ:TS_TYPE_RSV; sdes:'Reserved'; ldes:'ITU-T|ISO/IEC Reserved)'),
  (strm_typ:$33; elem_typ:TS_TYPE_RSV; sdes:'Reserved'; ldes:'ITU-T|ISO/IEC Reserved)'),
  (strm_typ:$34; elem_typ:TS_TYPE_RSV; sdes:'Reserved'; ldes:'ITU-T|ISO/IEC Reserved)'),
  (strm_typ:$35; elem_typ:TS_TYPE_RSV; sdes:'Reserved'; ldes:'ITU-T|ISO/IEC Reserved)'),
  (strm_typ:$36; elem_typ:TS_TYPE_RSV; sdes:'Reserved'; ldes:'ITU-T|ISO/IEC Reserved)'),
  (strm_typ:$37; elem_typ:TS_TYPE_RSV; sdes:'Reserved'; ldes:'ITU-T|ISO/IEC Reserved)'),
  (strm_typ:$38; elem_typ:TS_TYPE_RSV; sdes:'Reserved'; ldes:'ITU-T|ISO/IEC Reserved)'),
  (strm_typ:$39; elem_typ:TS_TYPE_RSV; sdes:'Reserved'; ldes:'ITU-T|ISO/IEC Reserved)'),
  (strm_typ:$3A; elem_typ:TS_TYPE_RSV; sdes:'Reserved'; ldes:'ITU-T|ISO/IEC Reserved)'),
  (strm_typ:$3B; elem_typ:TS_TYPE_RSV; sdes:'Reserved'; ldes:'ITU-T|ISO/IEC Reserved)'),
  (strm_typ:$3C; elem_typ:TS_TYPE_RSV; sdes:'Reserved'; ldes:'ITU-T|ISO/IEC Reserved)'),
  (strm_typ:$3D; elem_typ:TS_TYPE_RSV; sdes:'Reserved'; ldes:'ITU-T|ISO/IEC Reserved)'),
  (strm_typ:$3E; elem_typ:TS_TYPE_RSV; sdes:'Reserved'; ldes:'ITU-T|ISO/IEC Reserved)'),
  (strm_typ:$3F; elem_typ:TS_TYPE_RSV; sdes:'Reserved'; ldes:'ITU-T|ISO/IEC Reserved)'),
  (strm_typ:$40; elem_typ:TS_TYPE_RSV; sdes:'Reserved'; ldes:'ITU-T|ISO/IEC Reserved)'),
  (strm_typ:$41; elem_typ:TS_TYPE_RSV; sdes:'Reserved'; ldes:'ITU-T|ISO/IEC Reserved)'),
  (strm_typ:$42; elem_typ:TS_TYPE_VID; sdes:'AVS'; ldes:'Chinese Advanced Video Standard'),
  (strm_typ:$43; elem_typ:TS_TYPE_RSV; sdes:'Reserved'; ldes:'ITU-T|ISO/IEC Reserved)'),
  (strm_typ:$44; elem_typ:TS_TYPE_RSV; sdes:'Reserved'; ldes:'ITU-T|ISO/IEC Reserved)'),
  (strm_typ:$45; elem_typ:TS_TYPE_RSV; sdes:'Reserved'; ldes:'ITU-T|ISO/IEC Reserved)'),
  (strm_typ:$46; elem_typ:TS_TYPE_RSV; sdes:'Reserved'; ldes:'ITU-T|ISO/IEC Reserved)'),
  (strm_typ:$47; elem_typ:TS_TYPE_RSV; sdes:'Reserved'; ldes:'ITU-T|ISO/IEC Reserved)'),
  (strm_typ:$48; elem_typ:TS_TYPE_RSV; sdes:'Reserved'; ldes:'ITU-T|ISO/IEC Reserved)'),
  (strm_typ:$49; elem_typ:TS_TYPE_RSV; sdes:'Reserved'; ldes:'ITU-T|ISO/IEC Reserved)'),
  (strm_typ:$4A; elem_typ:TS_TYPE_RSV; sdes:'Reserved'; ldes:'ITU-T|ISO/IEC Reserved)'),
  (strm_typ:$4B; elem_typ:TS_TYPE_RSV; sdes:'Reserved'; ldes:'ITU-T|ISO/IEC Reserved)'),
  (strm_typ:$4C; elem_typ:TS_TYPE_RSV; sdes:'Reserved'; ldes:'ITU-T|ISO/IEC Reserved)'),
  (strm_typ:$4D; elem_typ:TS_TYPE_RSV; sdes:'Reserved'; ldes:'ITU-T|ISO/IEC Reserved)'),
  (strm_typ:$4E; elem_typ:TS_TYPE_RSV; sdes:'Reserved'; ldes:'ITU-T|ISO/IEC Reserved)'),
  (strm_typ:$4F; elem_typ:TS_TYPE_RSV; sdes:'Reserved'; ldes:'ITU-T|ISO/IEC Reserved)'),
  (strm_typ:$50; elem_typ:TS_TYPE_RSV; sdes:'Reserved'; ldes:'ITU-T|ISO/IEC Reserved)'),
  (strm_typ:$51; elem_typ:TS_TYPE_RSV; sdes:'Reserved'; ldes:'ITU-T|ISO/IEC Reserved)'),
  (strm_typ:$52; elem_typ:TS_TYPE_RSV; sdes:'Reserved'; ldes:'ITU-T|ISO/IEC Reserved)'),
  (strm_typ:$53; elem_typ:TS_TYPE_RSV; sdes:'Reserved'; ldes:'ITU-T|ISO/IEC Reserved)'),
  (strm_typ:$54; elem_typ:TS_TYPE_RSV; sdes:'Reserved'; ldes:'ITU-T|ISO/IEC Reserved)'),
  (strm_typ:$55; elem_typ:TS_TYPE_RSV; sdes:'Reserved'; ldes:'ITU-T|ISO/IEC Reserved)'),
  (strm_typ:$56; elem_typ:TS_TYPE_RSV; sdes:'Reserved'; ldes:'ITU-T|ISO/IEC Reserved)'),
  (strm_typ:$57; elem_typ:TS_TYPE_RSV; sdes:'Reserved'; ldes:'ITU-T|ISO/IEC Reserved)'),
  (strm_typ:$58; elem_typ:TS_TYPE_RSV; sdes:'Reserved'; ldes:'ITU-T|ISO/IEC Reserved)'),
  (strm_typ:$59; elem_typ:TS_TYPE_RSV; sdes:'Reserved'; ldes:'ITU-T|ISO/IEC Reserved)'),
  (strm_typ:$5A; elem_typ:TS_TYPE_RSV; sdes:'Reserved'; ldes:'ITU-T|ISO/IEC Reserved)'),
  (strm_typ:$5B; elem_typ:TS_TYPE_RSV; sdes:'Reserved'; ldes:'ITU-T|ISO/IEC Reserved)'),
  (strm_typ:$5C; elem_typ:TS_TYPE_RSV; sdes:'Reserved'; ldes:'ITU-T|ISO/IEC Reserved)'),
  (strm_typ:$5D; elem_typ:TS_TYPE_RSV; sdes:'Reserved'; ldes:'ITU-T|ISO/IEC Reserved)'),
  (strm_typ:$5E; elem_typ:TS_TYPE_RSV; sdes:'Reserved'; ldes:'ITU-T|ISO/IEC Reserved)'),
  (strm_typ:$5F; elem_typ:TS_TYPE_RSV; sdes:'Reserved'; ldes:'ITU-T|ISO/IEC Reserved)'),
  (strm_typ:$60; elem_typ:TS_TYPE_RSV; sdes:'Reserved'; ldes:'ITU-T|ISO/IEC Reserved)'),
  (strm_typ:$61; elem_typ:TS_TYPE_RSV; sdes:'Reserved'; ldes:'ITU-T|ISO/IEC Reserved)'),
  (strm_typ:$62; elem_typ:TS_TYPE_RSV; sdes:'Reserved'; ldes:'ITU-T|ISO/IEC Reserved)'),
  (strm_typ:$63; elem_typ:TS_TYPE_RSV; sdes:'Reserved'; ldes:'ITU-T|ISO/IEC Reserved)'),
  (strm_typ:$64; elem_typ:TS_TYPE_RSV; sdes:'Reserved'; ldes:'ITU-T|ISO/IEC Reserved)'),
  (strm_typ:$65; elem_typ:TS_TYPE_RSV; sdes:'Reserved'; ldes:'ITU-T|ISO/IEC Reserved)'),
  (strm_typ:$66; elem_typ:TS_TYPE_RSV; sdes:'Reserved'; ldes:'ITU-T|ISO/IEC Reserved)'),
  (strm_typ:$67; elem_typ:TS_TYPE_RSV; sdes:'Reserved'; ldes:'ITU-T|ISO/IEC Reserved)'),
  (strm_typ:$68; elem_typ:TS_TYPE_RSV; sdes:'Reserved'; ldes:'ITU-T|ISO/IEC Reserved)'),
  (strm_typ:$69; elem_typ:TS_TYPE_RSV; sdes:'Reserved'; ldes:'ITU-T|ISO/IEC Reserved)'),
  (strm_typ:$6A; elem_typ:TS_TYPE_RSV; sdes:'Reserved'; ldes:'ITU-T|ISO/IEC Reserved)'),
  (strm_typ:$6B; elem_typ:TS_TYPE_RSV; sdes:'Reserved'; ldes:'ITU-T|ISO/IEC Reserved)'),
  (strm_typ:$6C; elem_typ:TS_TYPE_RSV; sdes:'Reserved'; ldes:'ITU-T|ISO/IEC Reserved)'),
  (strm_typ:$6D; elem_typ:TS_TYPE_RSV; sdes:'Reserved'; ldes:'ITU-T|ISO/IEC Reserved)'),
  (strm_typ:$6E; elem_typ:TS_TYPE_RSV; sdes:'Reserved'; ldes:'ITU-T|ISO/IEC Reserved)'),
  (strm_typ:$6F; elem_typ:TS_TYPE_RSV; sdes:'Reserved'; ldes:'ITU-T|ISO/IEC Reserved)'),
  (strm_typ:$70; elem_typ:TS_TYPE_RSV; sdes:'Reserved'; ldes:'ITU-T|ISO/IEC Reserved)'),
  (strm_typ:$71; elem_typ:TS_TYPE_RSV; sdes:'Reserved'; ldes:'ITU-T|ISO/IEC Reserved)'),
  (strm_typ:$72; elem_typ:TS_TYPE_RSV; sdes:'Reserved'; ldes:'ITU-T|ISO/IEC Reserved)'),
  (strm_typ:$73; elem_typ:TS_TYPE_RSV; sdes:'Reserved'; ldes:'ITU-T|ISO/IEC Reserved)'),
  (strm_typ:$74; elem_typ:TS_TYPE_RSV; sdes:'Reserved'; ldes:'ITU-T|ISO/IEC Reserved)'),
  (strm_typ:$75; elem_typ:TS_TYPE_RSV; sdes:'Reserved'; ldes:'ITU-T|ISO/IEC Reserved)'),
  (strm_typ:$76; elem_typ:TS_TYPE_RSV; sdes:'Reserved'; ldes:'ITU-T|ISO/IEC Reserved)'),
  (strm_typ:$77; elem_typ:TS_TYPE_RSV; sdes:'Reserved'; ldes:'ITU-T|ISO/IEC Reserved)'),
  (strm_typ:$78; elem_typ:TS_TYPE_RSV; sdes:'Reserved'; ldes:'ITU-T|ISO/IEC Reserved)'),
  (strm_typ:$79; elem_typ:TS_TYPE_RSV; sdes:'Reserved'; ldes:'ITU-T|ISO/IEC Reserved)'),
  (strm_typ:$7A; elem_typ:TS_TYPE_RSV; sdes:'Reserved'; ldes:'ITU-T|ISO/IEC Reserved)'),
  (strm_typ:$7B; elem_typ:TS_TYPE_RSV; sdes:'Reserved'; ldes:'ITU-T|ISO/IEC Reserved)'),
  (strm_typ:$7C; elem_typ:TS_TYPE_RSV; sdes:'Reserved'; ldes:'ITU-T|ISO/IEC Reserved)'),
  (strm_typ:$7D; elem_typ:TS_TYPE_RSV; sdes:'Reserved'; ldes:'ITU-T|ISO/IEC Reserved)'),
  (strm_typ:$7E; elem_typ:TS_TYPE_RSV; sdes:'Reserved'; ldes:'ITU-T|ISO/IEC Reserved)'),
  (strm_typ:$7F; elem_typ:TS_TYPE_USR; sdes:'IPMP'; ldes:'ISO/IEC 13818-11 IPMP (DRM)'),
  (strm_typ:$80; elem_typ:TS_TYPE_VID; sdes:'SVAC LPCM'; ldes:'ITU-T Rec. H.262 and ISO/IEC 13818-2 with DES-64-CBC or PCM audio for Blu-ray'),
  (strm_typ:$81; elem_typ:TS_TYPE_AUD; sdes:'AC3'; ldes:'Dolby Digital (AC-3) up to six channel audio for ATSC and Blu-ray'),
  (strm_typ:$82; elem_typ:TS_TYPE_AUD; sdes:'DTS'; ldes:'SCTE subtitle or DTS 6 channel audio for Blu-ray'),
  (strm_typ:$83; elem_typ:TS_TYPE_AUD; sdes:'MLP'; ldes:'Dolby TrueHD lossless audio for Blu-ray'),
  (strm_typ:$84; elem_typ:TS_TYPE_AUD; sdes:'E-AC3'; ldes:'Dolby Digital Plus (enhanced AC-3) up to 16 channel audio for Blu-ray'),
  (strm_typ:$85; elem_typ:TS_TYPE_AUD; sdes:'DTS HD'; ldes:'DTS 8 channel audio for Blu-ray'),
  (strm_typ:$86; elem_typ:TS_TYPE_AUD; sdes:'DTS HD_XLL'; ldes:'SCTE-35[5] digital program insertion cue message or '+
                                                               'DTS 8 channel lossless audio for Blu-ray'),
  (strm_typ:$87; elem_typ:TS_TYPE_AUD; sdes:'E-AC3'; ldes:'Dolby Digital Plus (enhanced AC-3) up to 16 channel audio for ATSC'),
  (strm_typ:$88; elem_typ:TS_TYPE_RSV; sdes:'Reserved'; ldes:'ITU-T|ISO/IEC Reserved)'),
  (strm_typ:$89; elem_typ:TS_TYPE_RSV; sdes:'Reserved'; ldes:'ITU-T|ISO/IEC Reserved)'),
  (strm_typ:$8A; elem_typ:TS_TYPE_RSV; sdes:'Reserved'; ldes:'ITU-T|ISO/IEC Reserved)'),
  (strm_typ:$8B; elem_typ:TS_TYPE_RSV; sdes:'Reserved'; ldes:'ITU-T|ISO/IEC Reserved)'),
  (strm_typ:$8C; elem_typ:TS_TYPE_RSV; sdes:'Reserved'; ldes:'ITU-T|ISO/IEC Reserved)'),
  (strm_typ:$8D; elem_typ:TS_TYPE_RSV; sdes:'Reserved'; ldes:'ITU-T|ISO/IEC Reserved)'),
  (strm_typ:$8E; elem_typ:TS_TYPE_RSV; sdes:'Reserved'; ldes:'ITU-T|ISO/IEC Reserved)'),
  (strm_typ:$8F; elem_typ:TS_TYPE_RSV; sdes:'Reserved'; ldes:'ITU-T|ISO/IEC Reserved)'),
  (strm_typ:$90; elem_typ:TS_TYPE_AUD; sdes:'G.711'; ldes:'Blu-ray Presentation Graphic Stream (subtitling)'),
  (strm_typ:$91; elem_typ:TS_TYPE_USR; sdes:'DSM CC'; ldes:'ATSC DSM CC Network Resources table '),
  (strm_typ:$92; elem_typ:TS_TYPE_AUD; sdes:'G.722.1'; ldes:'G.722.1'),
  (strm_typ:$93; elem_typ:TS_TYPE_AUD; sdes:'G.723.1'; ldes:'G.723.1'),
  (strm_typ:$94; elem_typ:TS_TYPE_RSV; sdes:'Reserved'; ldes:'ITU-T|ISO/IEC Reserved)'),
  (strm_typ:$95; elem_typ:TS_TYPE_RSV; sdes:'Reserved'; ldes:'ITU-T|ISO/IEC Reserved)'),
  (strm_typ:$96; elem_typ:TS_TYPE_RSV; sdes:'Reserved'; ldes:'ITU-T|ISO/IEC Reserved)'),
  (strm_typ:$97; elem_typ:TS_TYPE_RSV; sdes:'Reserved'; ldes:'ITU-T|ISO/IEC Reserved)'),
  (strm_typ:$98; elem_typ:TS_TYPE_RSV; sdes:'Reserved'; ldes:'ITU-T|ISO/IEC Reserved)'),
  (strm_typ:$99; elem_typ:TS_TYPE_AUD; sdes:'G.729'; ldes:'G.729'),
  (strm_typ:$9A; elem_typ:TS_TYPE_AUD; sdes:'AMR-NB'; ldes:'AMR-NB'),
  (strm_typ:$9B; elem_typ:TS_TYPE_AUD; sdes:'SVAC'; ldes:'SVAC'),
  (strm_typ:$9C; elem_typ:TS_TYPE_RSV; sdes:'Reserved'; ldes:'ITU-T|ISO/IEC Reserved)'),
  (strm_typ:$9D; elem_typ:TS_TYPE_RSV; sdes:'Reserved'; ldes:'ITU-T|ISO/IEC Reserved)'),
  (strm_typ:$9E; elem_typ:TS_TYPE_RSV; sdes:'Reserved'; ldes:'ITU-T|ISO/IEC Reserved)'),
  (strm_typ:$9F; elem_typ:TS_TYPE_RSV; sdes:'Reserved'; ldes:'ITU-T|ISO/IEC Reserved)'),
  (strm_typ:$A0; elem_typ:TS_TYPE_RSV; sdes:'Reserved'; ldes:'ITU-T|ISO/IEC Reserved)'),
  (strm_typ:$A1; elem_typ:TS_TYPE_AUD; sdes:'DDP_2'; ldes:'Dolby Digital Plus'),
  (strm_typ:$A2; elem_typ:TS_TYPE_AUD; sdes:'DTS HD_2'; ldes:'DTS HD_2'),
  (strm_typ:$A3; elem_typ:TS_TYPE_RSV; sdes:'Reserved'; ldes:'ITU-T|ISO/IEC Reserved)'),
  (strm_typ:$A4; elem_typ:TS_TYPE_RSV; sdes:'Reserved'; ldes:'ITU-T|ISO/IEC Reserved)'),
  (strm_typ:$A5; elem_typ:TS_TYPE_RSV; sdes:'Reserved'; ldes:'ITU-T|ISO/IEC Reserved)'),
  (strm_typ:$A6; elem_typ:TS_TYPE_RSV; sdes:'Reserved'; ldes:'ITU-T|ISO/IEC Reserved)'),
  (strm_typ:$A7; elem_typ:TS_TYPE_RSV; sdes:'Reserved'; ldes:'ITU-T|ISO/IEC Reserved)'),
  (strm_typ:$A8; elem_typ:TS_TYPE_RSV; sdes:'Reserved'; ldes:'ITU-T|ISO/IEC Reserved)'),
  (strm_typ:$A9; elem_typ:TS_TYPE_RSV; sdes:'Reserved'; ldes:'ITU-T|ISO/IEC Reserved)'),
  (strm_typ:$AA; elem_typ:TS_TYPE_RSV; sdes:'Reserved'; ldes:'ITU-T|ISO/IEC Reserved)'),
  (strm_typ:$AB; elem_typ:TS_TYPE_RSV; sdes:'Reserved'; ldes:'ITU-T|ISO/IEC Reserved)'),
  (strm_typ:$AC; elem_typ:TS_TYPE_RSV; sdes:'Reserved'; ldes:'ITU-T|ISO/IEC Reserved)'),
  (strm_typ:$AD; elem_typ:TS_TYPE_RSV; sdes:'Reserved'; ldes:'ITU-T|ISO/IEC Reserved)'),
  (strm_typ:$AE; elem_typ:TS_TYPE_RSV; sdes:'Reserved'; ldes:'ITU-T|ISO/IEC Reserved)'),
  (strm_typ:$AF; elem_typ:TS_TYPE_RSV; sdes:'Reserved'; ldes:'ITU-T|ISO/IEC Reserved)'),
  (strm_typ:$B0; elem_typ:TS_TYPE_RSV; sdes:'Reserved'; ldes:'ITU-T|ISO/IEC Reserved)'),
  (strm_typ:$B1; elem_typ:TS_TYPE_RSV; sdes:'Reserved'; ldes:'ITU-T|ISO/IEC Reserved)'),
  (strm_typ:$B2; elem_typ:TS_TYPE_RSV; sdes:'Reserved'; ldes:'ITU-T|ISO/IEC Reserved)'),
  (strm_typ:$B3; elem_typ:TS_TYPE_RSV; sdes:'Reserved'; ldes:'ITU-T|ISO/IEC Reserved)'),
  (strm_typ:$B4; elem_typ:TS_TYPE_RSV; sdes:'Reserved'; ldes:'ITU-T|ISO/IEC Reserved)'),
  (strm_typ:$B5; elem_typ:TS_TYPE_RSV; sdes:'Reserved'; ldes:'ITU-T|ISO/IEC Reserved)'),
  (strm_typ:$B6; elem_typ:TS_TYPE_RSV; sdes:'Reserved'; ldes:'ITU-T|ISO/IEC Reserved)'),
  (strm_typ:$B7; elem_typ:TS_TYPE_RSV; sdes:'Reserved'; ldes:'ITU-T|ISO/IEC Reserved)'),
  (strm_typ:$B8; elem_typ:TS_TYPE_RSV; sdes:'Reserved'; ldes:'ITU-T|ISO/IEC Reserved)'),
  (strm_typ:$B9; elem_typ:TS_TYPE_RSV; sdes:'Reserved'; ldes:'ITU-T|ISO/IEC Reserved)'),
  (strm_typ:$BA; elem_typ:TS_TYPE_RSV; sdes:'Reserved'; ldes:'ITU-T|ISO/IEC Reserved)'),
  (strm_typ:$BB; elem_typ:TS_TYPE_RSV; sdes:'Reserved'; ldes:'ITU-T|ISO/IEC Reserved)'),
  (strm_typ:$BC; elem_typ:TS_TYPE_RSV; sdes:'Reserved'; ldes:'ITU-T|ISO/IEC Reserved)'),
  (strm_typ:$BD; elem_typ:TS_TYPE_RSV; sdes:'Reserved'; ldes:'ITU-T|ISO/IEC Reserved)'),
  (strm_typ:$BE; elem_typ:TS_TYPE_RSV; sdes:'Reserved'; ldes:'ITU-T|ISO/IEC Reserved)'),
  (strm_typ:$BF; elem_typ:TS_TYPE_RSV; sdes:'Reserved'; ldes:'ITU-T|ISO/IEC Reserved)'),
  (strm_typ:$C0; elem_typ:TS_TYPE_USR; sdes:'Text'; ldes:'DigiCipher II text'),
  (strm_typ:$C1; elem_typ:TS_TYPE_AUD; sdes:'AC-3'; ldes:'Dolby Digital (AC-3) up to six channel audio '+
                                                         'with AES-128-CBC data encryption'),
  (strm_typ:$C2; elem_typ:TS_TYPE_AUD; sdes:'DSM CC'; ldes:'ATSC DSM CC synchronous data or Dolby Digital Plus up'+
                                                           'to 16 channel audio with AES-128-CBC data encryption'),
  (strm_typ:$C3; elem_typ:TS_TYPE_RSV; sdes:'Reserved'; ldes:'ITU-T|ISO/IEC Reserved)'),
  (strm_typ:$C4; elem_typ:TS_TYPE_RSV; sdes:'Reserved'; ldes:'ITU-T|ISO/IEC Reserved)'),
  (strm_typ:$C5; elem_typ:TS_TYPE_RSV; sdes:'Reserved'; ldes:'ITU-T|ISO/IEC Reserved)'),
  (strm_typ:$C6; elem_typ:TS_TYPE_RSV; sdes:'Reserved'; ldes:'ITU-T|ISO/IEC Reserved)'),
  (strm_typ:$C7; elem_typ:TS_TYPE_RSV; sdes:'Reserved'; ldes:'ITU-T|ISO/IEC Reserved)'),
  (strm_typ:$C8; elem_typ:TS_TYPE_RSV; sdes:'Reserved'; ldes:'ITU-T|ISO/IEC Reserved)'),
  (strm_typ:$C9; elem_typ:TS_TYPE_RSV; sdes:'Reserved'; ldes:'ITU-T|ISO/IEC Reserved)'),
  (strm_typ:$CA; elem_typ:TS_TYPE_RSV; sdes:'Reserved'; ldes:'ITU-T|ISO/IEC Reserved)'),
  (strm_typ:$CB; elem_typ:TS_TYPE_RSV; sdes:'Reserved'; ldes:'ITU-T|ISO/IEC Reserved)'),
  (strm_typ:$CC; elem_typ:TS_TYPE_RSV; sdes:'Reserved'; ldes:'ITU-T|ISO/IEC Reserved)'),
  (strm_typ:$CD; elem_typ:TS_TYPE_RSV; sdes:'Reserved'; ldes:'ITU-T|ISO/IEC Reserved)'),
  (strm_typ:$CE; elem_typ:TS_TYPE_RSV; sdes:'Reserved'; ldes:'ITU-T|ISO/IEC Reserved)'),
  (strm_typ:$CF; elem_typ:TS_TYPE_AUD; sdes:'AAC AES'; ldes:'ISO/IEC 13818-7 ADTS AAC with AES-128-CBC frame encryption'),
  (strm_typ:$D0; elem_typ:TS_TYPE_RSV; sdes:'Reserved'; ldes:'ITU-T|ISO/IEC Reserved)'),
  (strm_typ:$D1; elem_typ:TS_TYPE_RSV; sdes:'Reserved'; ldes:'ITU-T|ISO/IEC Reserved)'),
  (strm_typ:$D2; elem_typ:TS_TYPE_RSV; sdes:'Reserved'; ldes:'ITU-T|ISO/IEC Reserved)'),
  (strm_typ:$D3; elem_typ:TS_TYPE_RSV; sdes:'Reserved'; ldes:'ITU-T|ISO/IEC Reserved)'),
  (strm_typ:$D4; elem_typ:TS_TYPE_RSV; sdes:'Reserved'; ldes:'ITU-T|ISO/IEC Reserved)'),
  (strm_typ:$D5; elem_typ:TS_TYPE_RSV; sdes:'Reserved'; ldes:'ITU-T|ISO/IEC Reserved)'),
  (strm_typ:$D6; elem_typ:TS_TYPE_RSV; sdes:'Reserved'; ldes:'ITU-T|ISO/IEC Reserved)'),
  (strm_typ:$D7; elem_typ:TS_TYPE_RSV; sdes:'Reserved'; ldes:'ITU-T|ISO/IEC Reserved)'),
  (strm_typ:$D8; elem_typ:TS_TYPE_RSV; sdes:'Reserved'; ldes:'ITU-T|ISO/IEC Reserved)'),
  (strm_typ:$D9; elem_typ:TS_TYPE_RSV; sdes:'Reserved'; ldes:'ITU-T|ISO/IEC Reserved)'),
  (strm_typ:$DA; elem_typ:TS_TYPE_RSV; sdes:'Reserved'; ldes:'ITU-T|ISO/IEC Reserved)'),
  (strm_typ:$DB; elem_typ:TS_TYPE_RSV; sdes:'Reserved'; ldes:'ITU-T|ISO/IEC Reserved)'),
  (strm_typ:$DC; elem_typ:TS_TYPE_RSV; sdes:'Reserved'; ldes:'ITU-T|ISO/IEC Reserved)'),
  (strm_typ:$DD; elem_typ:TS_TYPE_RSV; sdes:'Reserved'; ldes:'ITU-T|ISO/IEC Reserved)'),
  (strm_typ:$DE; elem_typ:TS_TYPE_RSV; sdes:'Reserved'; ldes:'ITU-T|ISO/IEC Reserved)'),
  (strm_typ:$DF; elem_typ:TS_TYPE_RSV; sdes:'Reserved'; ldes:'ITU-T|ISO/IEC Reserved)'),
  (strm_typ:$E0; elem_typ:TS_TYPE_RSV; sdes:'Reserved'; ldes:'ITU-T|ISO/IEC Reserved)'),
  (strm_typ:$E1; elem_typ:TS_TYPE_RSV; sdes:'Reserved'; ldes:'ITU-T|ISO/IEC Reserved)'),
  (strm_typ:$E2; elem_typ:TS_TYPE_RSV; sdes:'Reserved'; ldes:'ITU-T|ISO/IEC Reserved)'),
  (strm_typ:$E3; elem_typ:TS_TYPE_RSV; sdes:'Reserved'; ldes:'ITU-T|ISO/IEC Reserved)'),
  (strm_typ:$E4; elem_typ:TS_TYPE_RSV; sdes:'Reserved'; ldes:'ITU-T|ISO/IEC Reserved)'),
  (strm_typ:$E5; elem_typ:TS_TYPE_RSV; sdes:'Reserved'; ldes:'ITU-T|ISO/IEC Reserved)'),
  (strm_typ:$E6; elem_typ:TS_TYPE_RSV; sdes:'Reserved'; ldes:'ITU-T|ISO/IEC Reserved)'),
  (strm_typ:$E7; elem_typ:TS_TYPE_RSV; sdes:'Reserved'; ldes:'ITU-T|ISO/IEC Reserved)'),
  (strm_typ:$E8; elem_typ:TS_TYPE_RSV; sdes:'Reserved'; ldes:'ITU-T|ISO/IEC Reserved)'),
  (strm_typ:$E9; elem_typ:TS_TYPE_RSV; sdes:'Reserved'; ldes:'ITU-T|ISO/IEC Reserved)'),
  (strm_typ:$EA; elem_typ:TS_TYPE_VID; sdes:'WMV-9'; ldes:'Microsoft Windows Media Video 9 (lower bit-rate video)'),
  (strm_typ:$EB; elem_typ:TS_TYPE_RSV; sdes:'Reserved'; ldes:'ITU-T|ISO/IEC Reserved)'),
  (strm_typ:$EC; elem_typ:TS_TYPE_RSV; sdes:'Reserved'; ldes:'ITU-T|ISO/IEC Reserved)'),
  (strm_typ:$ED; elem_typ:TS_TYPE_RSV; sdes:'Reserved'; ldes:'ITU-T|ISO/IEC Reserved)'),
  (strm_typ:$EE; elem_typ:TS_TYPE_RSV; sdes:'Reserved'; ldes:'ITU-T|ISO/IEC Reserved)'),
  (strm_typ:$EF; elem_typ:TS_TYPE_RSV; sdes:'Reserved'; ldes:'ITU-T|ISO/IEC Reserved)'),
  (strm_typ:$F0; elem_typ:TS_TYPE_RSV; sdes:'Reserved'; ldes:'ITU-T|ISO/IEC Reserved)'),
  (strm_typ:$F1; elem_typ:TS_TYPE_ECM; sdes:'ECM'; ldes:'ECM'),
  (strm_typ:$F2; elem_typ:TS_TYPE_AUD; sdes:'DRA'; ldes:'Digital Rise Audio'),
  (strm_typ:$F3; elem_typ:TS_TYPE_RSV; sdes:'Reserved'; ldes:'ITU-T|ISO/IEC Reserved)'),
  (strm_typ:$F4; elem_typ:TS_TYPE_RSV; sdes:'Reserved'; ldes:'ITU-T|ISO/IEC Reserved)'),
  (strm_typ:$F5; elem_typ:TS_TYPE_RSV; sdes:'Reserved'; ldes:'ITU-T|ISO/IEC Reserved)'),
  (strm_typ:$F6; elem_typ:TS_TYPE_RSV; sdes:'Reserved'; ldes:'ITU-T|ISO/IEC Reserved)'),
  (strm_typ:$F7; elem_typ:TS_TYPE_RSV; sdes:'Reserved'; ldes:'ITU-T|ISO/IEC Reserved)'),
  (strm_typ:$F8; elem_typ:TS_TYPE_RSV; sdes:'Reserved'; ldes:'ITU-T|ISO/IEC Reserved)'),
  (strm_typ:$F9; elem_typ:TS_TYPE_RSV; sdes:'Reserved'; ldes:'ITU-T|ISO/IEC Reserved)'),
  (strm_typ:$FA; elem_typ:TS_TYPE_RSV; sdes:'Reserved'; ldes:'ITU-T|ISO/IEC Reserved)'),
  (strm_typ:$FB; elem_typ:TS_TYPE_RSV; sdes:'Reserved'; ldes:'ITU-T|ISO/IEC Reserved)'),
  (strm_typ:$FC; elem_typ:TS_TYPE_RSV; sdes:'Reserved'; ldes:'ITU-T|ISO/IEC Reserved)'),
  (strm_typ:$FD; elem_typ:TS_TYPE_RSV; sdes:'Reserved'; ldes:'ITU-T|ISO/IEC Reserved)'),
  (strm_typ:$FE; elem_typ:TS_TYPE_RSV; sdes:'Reserved'; ldes:'ITU-T|ISO/IEC Reserved)'),
  (strm_typ:$FF; elem_typ:TS_TYPE_UNO; sdes:'UNKNOWN'; ldes:'Unknown stream'));

  // Profiles
  // $42 Constrained Baseline Profile (CBP, 66 with constraint set 1)

implementation

end.

